#ifndef IMPORT_H_DEFINED_2014_10_12_ELEAFLRCWYMEMDNHQSDALBVAKKNMNM
#define IMPORT_H_DEFINED_2014_10_12_ELEAFLRCWYMEMDNHQSDALBVAKKNMNM
 
#include <vector>
#include <string>

int import_(const std::vector<std::string>& vec);

#endif/*IMPORT_H_DEFINED_2014_10_12_ELEAFLRCWYMEMDNHQSDALBVAKKNMNM*/
